manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: sepidre
      url-base: https://github.com/SepiDre
  projects:
    - name: zmk-german
      remote: sepidre
      revision: sofle
      import: app/west.yml
  self:
    path: config